;; (DEFINE-CONFIGURATION BUFFER
;;   ((DEFAULT-MODES (APPEND '(NYXT::EMACS-MODE NYXT::DARK-MODE NYXT::reduce-tracking-mode ) %SLOT-DEFAULT%))))

(DEFINE-CONFIGURATION BUFFER
  ((DEFAULT-MODES (APPEND '(NYXT::EMACS-MODE NYXT::DARK-MODE  ) %SLOT-DEFAULT%))))

